### ISSUE TITLE
Development Branch Question: Item card shows token ID

### ISSUE THREAD

**Issue by Maitlans** [enjin/enjincraft#65]
Is there a way to hide/remove the ID from being shown in the card when you hover over the item, same with the "withdraw" since it alters the item aesthetics as well as some plugins won't recognize the item because the lore has been altered? Thank you
![image](https://user-images.githubusercontent.com/51733032/86540867-1b636900-bed6-11ea-83f1-6a25e6af3c83.png)
![image](https://user-images.githubusercontent.com/51733032/86540871-23bba400-bed6-11ea-89e8-bf8dc0c00d61.png)

Here's what it originally looked like:
![image](https://user-images.githubusercontent.com/51733032/86540919-6a110300-bed6-11ea-986a-6151bb042b4c.png)

**Comment by Favorlock** [comment]
When an item is checked out these are removed from an item. In wallet we need to communicate some state like whether the item is withdrawable from the wallet or not.

**Comment by Maitlans** [comment]
The second image is when it's withdrawn, it still leaves the extra empty lore and the token ID.

**Comment by Maitlans** [comment]
Hi I think It'll be more visibly pleasing and less confusing if it was placed something similar to this as it won't alter with the items default lore. As well as if the Token ID wasn't there since there isn't really any use for the player to know or see it. Please let me know what you think of this concept, thank you and keep up the awesome work!
![image](https://user-images.githubusercontent.com/51733032/88004765-b6af2d80-cad5-11ea-8896-3c2a7da493a2.png)

**Comment by Favorlock** [comment]
Checked out items aren't supposed to have any wallet metadata in the lore. This should be fixed when we're able to release a new version. Wallet metadata will always be shown at the top of the lore for the items seen in the wallet though as we want to make sure that stuff is visible first and foremost. The token id isn't important to see, but withdrawable is because it represents whether a token can be withdrawn from the wallet or not. The reason why we wouldn't want to show it at the bottom is to avoid a situation where a server owner specifies a lore that is long enough to push the metadata at the bottom off-screen, so this is a meaningful design choice on our part.

**Comment by Maitlans** [comment]
Hey, I noticed that the Item ID was removed as of the latest development when I tested, should be good for issue to be closed unless there's something else? Thanks!
