### ISSUE TITLE
[Suggestion] Send & Receive Requests

### ISSUE THREAD

**Issue by Maitlans** [enjin/enjincraft#68]
Server Owners can set up custom send requests to a player's Enjin wallet requesting an item or a set of items. After the player accepts the server could automatically perform an action that could be such as a command. This could be to finish a quest or other custom actions performed by console run commands.

I'm not sure if it's possible to request Enjin Coin directly from a user's wallet but if it is possible this would make way for in-game purchasing of collectibles using Enjin Coin. User makes a request that they want to buy something, they get a request and after they accept it the item is sent, or if it's possible to do it similar to how trading works where you can make a request of sending and receiving at the same time. 

Lost Relics/Forgotten Artifacts uses a system similar to this to do different various things in their game, I think it could be very fitting for Minecraft and open more possibilities. Using this they manage to recycle many of their collectibles ending up again on the Owner's wallet and redistributing them out again. 

Please let me know what you think and please correct me if I got any information wrong, thank you.

**Comment by Favorlock** [comment]
Hi @Maitlan, regarding your suggestion What you described is the same thing as a trade, so someone would just need to implement desired functionality using CreateTrade, CompleteTrade, and events. I don't see this being a feature we'd implement in EnjinCraft since it could be created as an extension. EnjinCraft is really just a plugin that provides the base functionality for integrating with ERC-1155 tokens. The main issue is that this suggestion really sounds more like a gameplay feature which we don't intend to implement gameplay mechanics into EnjinCraft as that would create far more complexity and difficulty to maintain.
